/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MENU;

import USUARIO.ManagerUsuarios;
import java.io.IOException;

/**
 *
 * @author Josue Gavidia
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    ManagerUsuarios managerUsers;

    public MenuPrincipal() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.REG_TAB.setVisible(false);

        try {
            managerUsers = new ManagerUsuarios();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        } catch (ClassNotFoundException e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN_MENU = new javax.swing.JPanel();
        REGISTER = new javax.swing.JButton();
        LOGIN = new javax.swing.JButton();
        REG_TAB = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        fullName = new javax.swing.JTextField();
        Reg_Checkout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);

        MAIN_MENU.setBackground(new java.awt.Color(51, 0, 0));
        MAIN_MENU.setPreferredSize(new java.awt.Dimension(1920, 1080));
        MAIN_MENU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        REGISTER.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        REGISTER.setText("REGISTRO");
        REGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERActionPerformed(evt);
            }
        });
        MAIN_MENU.add(REGISTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 330, 90));

        LOGIN.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        LOGIN.setText("INICIO DE SESION");
        MAIN_MENU.add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 330, 90));

        REG_TAB.setBackground(new java.awt.Color(51, 0, 0));
        REG_TAB.setPreferredSize(new java.awt.Dimension(1920, 1080));
        REG_TAB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel1.setText("NOMBRE COMPLETO");
        REG_TAB.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 350, 100));

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel2.setText("USUARIO");
        REG_TAB.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 230, 100));

        jLabel3.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel3.setText("CONTRASEñA");
        REG_TAB.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 230, 100));

        us.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        us.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REG_TAB.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 550, 80));

        pass.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REG_TAB.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 550, 80));

        fullName.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        fullName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        REG_TAB.add(fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 550, 80));

        Reg_Checkout.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        Reg_Checkout.setText("REGISTRARSE");
        REG_TAB.add(Reg_Checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 690, 330, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_MENU, javax.swing.GroupLayout.DEFAULT_SIZE, 1936, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(REG_TAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_MENU, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(REG_TAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERActionPerformed
        this.REG_TAB.setVisible(true);
        this.MAIN_MENU.setVisible(false);
    }//GEN-LAST:event_REGISTERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LOGIN;
    private javax.swing.JPanel MAIN_MENU;
    private javax.swing.JButton REGISTER;
    private javax.swing.JPanel REG_TAB;
    private javax.swing.JButton Reg_Checkout;
    private javax.swing.JTextField fullName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField us;
    // End of variables declaration//GEN-END:variables
}
